# Usa Node.js 20 como base
FROM node:20-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos essenciais para instalar dependências
COPY package*.json ./

# Instala todas as dependências (dev e prod)
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Expõe a porta 8080
EXPOSE 8080

# Comando para iniciar o backend
CMD ["node", "dist/server.js"]